version: "3.9"

services:
  # container for php-fpm
  php:
    image: php:fpm
    container_name: php
    volumes:
      - ./code:/code
      - ./conf/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - code-network

  #  container for nginx webserver
  server:
    image: nginx:latest
    container_name: enginex
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    depends_on:
      - php

  # # container for mysql
  # database:
  #   container_name: database
  #   image: mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=fanto237
  #     - MYSQL_USER=fanto
  #     - MYSQL_PASSWORD=fantobase
  #     - MYSQL_DATABASE=Testdb
  #   volumes:
  #     - ./database:/var/lib/mysql
  #   networks:
  #     - code-network

networks:
  code-network:
    driver: bridge
